### ISSUE TITLE
Add support for multiple gameservers

### ISSUE THREAD

**Issue by frearkdev** [Project-Reload/Reload-Backend#11]
Please add support for multiple gameservers so you can host multiple regions on this backend, or is that already possible? If yes, how?

**Comment by VoxyB89** [comment]
Support For Multiple Gameservers Probably will be possible if you modify the code to also allow hosting for example on eu and na at the same time + all of the gameserver will have to be on seperate machines if you dont wanna make your pc explode and if you dont wanna have 4+ ports opened for 4 gameservers (I take Into an example your trying to make a project)

If you have any other questions dm me on discord (i am also making a project, if thats what your doing), Username: avrixfal

**Comment by zeroaltud** [comment]
> Support For Multiple Gameservers Probably will be possible if you modify the code to also allow hosting for example on eu and na at the same time + all of the gameserver will have to be on seperate machines if you dont wanna make your pc explode and if you dont wanna have 4+ ports opened for 4 gameservers (I take Into an example your trying to make a project)
> 
> If you have any other questions dm me on discord (i am also making a project, if thats what your doing), Username: avrixfal

added you on discord

**Comment by zeroaltud** [comment]
> Please add support for multiple gameservers so you can host multiple regions on this backend, or is that already possible? If yes, how?

added it n my github
