### ISSUE TITLE
Arena and tournament Pleaseeee 

### ISSUE THREAD

**Issue by 1kevijn** [Project-Reload/Reload-Backend#12]
Arena and tournament with assets usw? PLEASE

**Comment by Drixxytec** [comment]
That's playlist, you have to find that yourself.

**Comment by ojotaa0124** [comment]
> That's playlist, you have to find that yourself.

um 😂

**Comment by lapin2266** [comment]
> That's playlist, you have to find that yourself.

How find the arena playlist ?

**Comment by Ducki67** [comment]
> > That's playlist, you have to find that yourself.
> 
> How find the arena playlist ?

u can find IDs here but u have to add the assets your self
https://fortnite-stats.azurewebsites.net/Playlists

**Comment by ILovePuppies9145** [comment]
> > > That's playlist, you have to find that yourself.
> > 
> > 
> > How find the arena playlist ?
> 
> u can find IDs here but u have to add the assets your self https://fortnite-stats.azurewebsites.net/Playlists

Yeah how to add it exactly?
