### ISSUE TITLE
Event's not starting.

### ISSUE THREAD

**Issue by PuppeDEV** [Project-Reload/Reload-Backend#19]
So i think u need a Loopkey to start events and the backend doesn't have that so plz add that or do smth to get events working.

**Comment by PuppeDEV** [comment]
Oh okay bcs for me i tried travis scott and it didn’t work

**Comment by PuppeDEV** [comment]
Or do i need to do smth?

**Comment by burlone0** [comment]
idk, prob ur reboot version are brk

**Comment by burlone0** [comment]
but i've a different reload version cuz i've update the backend and today / tomorrow i'll release the new ver

**Comment by PuppeDEV** [comment]
Okay i maybe test some c1 event today and tomorrow with new version

**Comment by xy8q** [comment]
shut up mr. skid

**Comment by PuppeDEV** [comment]
Btw i just wanna ask why but still even all of these updates travis scott event doesn’t start. Do ANYONE have any kind of solution
