### ISSUE TITLE
Vbucks Kils 

### ISSUE THREAD

**Issue by NuZiuki240Hz** [Project-Reload/Reload-Backend#2]
oon backend or GS vbucks and kills and win? Reload-Backend

**Comment by burlone0** [comment]
Bro at most I can do the part for the backend, for the gameserver you will have to do it yourself 💀

**Comment by ItzAndingly** [comment]
Sigma male

**Comment by NuZiuki240Hz** [comment]
Okay 👌

**Comment by NuZiuki240Hz** [comment]
and for the Create an automatic shop how are you going to do it? because I have an automatic shop thingy if you want I could put it on discord and you could look at it.

**Comment by burlone0** [comment]
Send in dm the automatic shop

**Comment by NuZiuki240Hz** [comment]
it's a bass of Lawin server V3 that a dev put the modification for me who put the shop automatic and whatever additional command like fulllocker and rotashop
