### ISSUE TITLE
no credits?

### ISSUE THREAD

**Issue by xy8q** [Project-Reload/Reload-Backend#20]
![image](https://github.com/user-attachments/assets/88045d85-3cee-4b01-9c02-33627926c025)

**Comment by burlone0** [comment]
uh? i've added all credits

**Comment by xy8q** [comment]
for momentum?

**Comment by ojotaa0124** [comment]
> for momentum? it's clearly momentum athena.json

it seems like your iq its on the ground, you dont understand, momentum took the athena file from lawinv2 so its the same thing, he just took the one from momentum so it has different loadouts.

**Comment by ojotaa0124** [comment]
> for momentum? it's clearly momentum athena.json

your iq is 0 right?

it doesnt matter if he took the athena file from momentum, its the same thing as lawinv2 athena file, actually, momentum took lawin's athena file...

**Comment by xy8q** [comment]
okay, but MOMENTUM have credits to lawin, but Reload stole from momentum, and gave no credits, mr retard

**Comment by burlone0** [comment]
bro if momentum gave credit to lawin because they used their defaultprofiles then I don't have to give any credit to momentum if the files are original from lawin
