### ISSUE TITLE
ADD QUESTS FOR SEASON X!!!

### ISSUE THREAD

**Issue by kostasIsHere123** [Project-Reload/Reload-Backend#25]
looking forward for quests, its for a project I'm working on!

**Comment by burlone0** [comment]
uh alr add quest on s10

**Comment by kostasIsHere123** [comment]
@burlone0 if you actually do it, I am gonna be so FUCKING HAPPY

**Comment by burlone0** [comment]
i've alr do it

**Comment by kostasIsHere123** [comment]
wait have you added seasonal quests? like the things to get the extra styles from skins or the scientist?

**Comment by burlone0** [comment]
ye i think

**Comment by kostasIsHere123** [comment]
they all say "currently unavailable"

**Comment by UniqueTomm** [comment]
> ye i think

which gameserver can i use that quests and level works?

**Comment by AmetTheCat** [comment]
> > ye i think
> 
> which gameserver can i use that quests and level works?

you need to program it into the gameserver so it can communicate with the backend

**Comment by UniqueTomm** [comment]
> > > ye i think
> > 
> > 
> > which gameserver can i use that quests and level works?
> 
> you need to program it into the gameserver so it can communicate with the backend

yeah but which gs should i use i dont think normal project reboot is good

**Comment by AmetTheCat** [comment]
idk

> > > > ye i think
> > > 
> > > 
> > > which gameserver can i use that quests and level works?
> > 
> > 
> > you need to program it into the gameserver so it can communicate with the backend
> 
> yeah but which gs should i use i dont think normal project reboot is good

idk why should reboot not be good?

**Comment by UniqueTomm** [comment]
> idk
> 
> > > > > ye i think
> > > > 
> > > > 
> > > > which gameserver can i use that quests and level works?
> > > 
> > > 
> > > you need to program it into the gameserver so it can communicate with the backend
> > 
> > 
> > yeah but which gs should i use i dont think normal project reboot is good
> 
> idk why should reboot not be good?

i only mean normal self builded reboot, because i want that he is sending an message when the gs started and ended but only when he started is supported

**Comment by AmetTheCat** [comment]
> > idk
> > > > > > ye i think
> > > > > 
> > > > > 
> > > > > which gameserver can i use that quests and level works?
> > > > 
> > > > 
> > > > you need to program it into the gameserver so it can communicate with the backend
> > > 
> > > 
> > > yeah but which gs should i use i dont think normal project reboot is good
> > 
> > 
> > idk why should reboot not be good?
> 
> i only mean normal self builded reboot, because i want that he is sending an message when the gs started and ended but only when he started is supported

yeah thats why you need to it yourself thats recommended if you want to start a "project" or what ever...

**Comment by UniqueTomm** [comment]
> > > idk
> > > > > > > ye i think
> > > > > > 
> > > > > > 
> > > > > > which gameserver can i use that quests and level works?
> > > > > 
> > > > > 
> > > > > you need to program it into the gameserver so it can communicate with the backend
> > > > 
> > > > 
> > > > yeah but which gs should i use i dont think normal project reboot is good
> > > 
> > > 
> > > idk why should reboot not be good?
> > 
> > 
> > i only mean normal self builded reboot, because i want that he is sending an message when the gs started and ended but only when he started is supported
> 
> yeah thats why you need to it yourself thats recommended if you want to start a "project" or what ever...

but idk where i can learn starting developing own backend + other things like gs or launcher

**Comment by UniqueTomm** [comment]
> > > > > idk
> > > > > > > > > ye i think
> > > > > > > > 
> > > > > > > > 
> > > > > > > > which gameserver can i use that quests and level works?
> > > > > > > 
> > > > > > > 
> > > > > > > you need to program it into the gameserver so it can communicate with the backend
> > > > > > 
> > > > > > 
> > > > > > yeah but which gs should i use i dont think normal project reboot is good
> > > > > 
> > > > > 
> > > > > idk why should reboot not be good?
> > > > 
> > > > 
> > > > i only mean normal self builded reboot, because i want that he is sending an message when the gs started and ended but only when he started is supported
> > > 
> > > 
> > > yeah thats why you need to it yourself thats recommended if you want to start a "project" or what ever...
> > 
> > 
> > but idk where i can learn starting developing own backend + other things like gs or launcher
> 
> you need to learn c++. typescript/javascript or maybe go and yeah

yh i know but idk where

**Comment by AmetTheCat** [comment]
> > > > > > idk
> > > > > > > > > > ye i think
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > which gameserver can i use that quests and level works?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > you need to program it into the gameserver so it can communicate with the backend
> > > > > > > 
> > > > > > > 
> > > > > > > yeah but which gs should i use i dont think normal project reboot is good
> > > > > > 
> > > > > > 
> > > > > > idk why should reboot not be good?
> > > > > 
> > > > > 
> > > > > i only mean normal self builded reboot, because i want that he is sending an message when the gs started and ended but only when he started is supported
> > > > 
> > > > 
> > > > yeah thats why you need to it yourself thats recommended if you want to start a "project" or what ever...
> > > 
> > > 
> > > but idk where i can learn starting developing own backend + other things like gs or launcher
> > 
> > 
> > you need to learn c++. typescript/javascript or maybe go and yeah
> 
> yh i know but idk where

YouTube or maybe ChatGPT ask him for help, he is an AI hes gonna help you for sure

**Comment by UniqueTomm** [comment]
okay i will try, thx for your answers

**Comment by AmetTheCat** [comment]
no problem :)

**Comment by UniqueTomm** [comment]
> no problem :)

is it okay when i give you my discord user?

**Comment by AmetTheCat** [comment]
yeah

**Comment by UniqueTomm** [comment]
> yeah

uniquetom_

**Comment by AmetTheCat** [comment]
added you
