### ISSUE TITLE
How can others log in my backend? (please help meee)

### ISSUE THREAD

**Issue by kostasIsHere123** [Project-Reload/Reload-Backend#26]
I have been having trouble with this soo (help pretty pleaseee)

**Comment by ProjectNeptuneMP** [comment]
If you host on a vps you just have to type your vps ip to log in. But if you host with your computer you need play it gg or radmin to let others connect to it. There is so many tutorials for it. I Recommend mineluke tutorials

**Comment by AjaxFNC-YT** [comment]
https://www.youtube.com/watch?v=3Bwu2pFiFlI&t=543s

**Comment by AjaxFNC-YT** [comment]
for playit.gg (he shows reboot in the video, but you get it)
