### ISSUE TITLE
Not an issue but a suggestion. Make Reload TCP Combatible

### ISSUE THREAD

**Issue by sonic11719** [Project-Reload/Reload-Backend#32]
If Reload is TCP compatible then you can have stuff like XMPP for seasons under S3. Someone coded it a while ago but never made it available to the public.

maybe matchmaking could work as well??
![image](https://github.com/user-attachments/assets/d72a6246-d08c-4784-9ddc-675b9495b555)

**Comment by burlone0** [comment]
wdym, give me more info

**Comment by sonic11719** [comment]
im not 100% sure about TCP servers but apparently you need like an 'OpenFire XMPP server and a SSL Certificate'. i found out about this stuff from this github issue for lawinv2
https://github.com/Lawin0129/LawinServerV2/issues/115
there was also another one made by 'kaonies' which no longer works, but it had tcp support and s0 servers worked.
https://github.com/kaonies/LawinServer-TCP

**Comment by burlone0** [comment]
ok I'll work on it

**Comment by sonic11719** [comment]
thx <3

**Comment by Ducki67** [comment]
is this still being worked or what ?

**Comment by VoxyB89** [comment]
> is this still being worked or what ?

yes it is no leaks yet tho 😃

**Comment by Ducki67** [comment]
> > is this still being worked or what ?
> 
> yes it is no leaks yet tho 😃

Prob no1 is working on this + it whould be better if theres a way to make a MM sor below s3 without any Domain or external TCP stuff


I would be happy if theres a way to do so

**Comment by VoxyB89** [comment]
> > > is this still being worked or what ?
> > 
> > 
> > yes it is no leaks yet tho 😃
> 
> Prob no1 is working on this + it whould be better if theres a way to make a MM sor below s3 without any Domain or external TCP stuff
> 
> I would be happy if theres a way to do so

without domain or external tcp (openfire) prob wont be possible due to early fn also using openfire (there own)
also yes we are working on it and we are testing in the background
