### ISSUE TITLE
parties don't seem to work?

### ISSUE THREAD

**Issue by kostasIsHere123** [Project-Reload/Reload-Backend#33]
This is my configuration, it shows that someone that I have friended is offline even though hes not. Please tell me how to fix
![Καταγραφήdsadasdsadadasdas](https://github.com/user-attachments/assets/cded5f12-64a8-4691-b653-c46710ca4fe8)

**Comment by sonic11719** [comment]
change from serverport=3551 to whatever your xmpp port is

**Comment by kostasIsHere123** [comment]
yeah, I switched the serverport to 80 which should be correct but it didn't seem to work

**Comment by sonic11719** [comment]
change 127.0.0.1 to your radmin ip

**Comment by kostasIsHere123** [comment]
I am not using radmin

**Comment by sonic11719** [comment]
what do u use then?

**Comment by kostasIsHere123** [comment]
my public ip

**Comment by sonic11719** [comment]
use that then. just dont give it to the public

**Comment by kostasIsHere123** [comment]
alr thanks, also theres no need from hiding your public ip from the public, its your private ip you should hide

**Comment by sonic11719** [comment]
ok just lmk if it works

**Comment by burlone0** [comment]
Prob it's ur pc / vps problem cuz i had the same problem, I think you have some application that conflicts with the backend xmpp

**Comment by kostasIsHere123** [comment]
thats weird, any idea what that app may be?
