### ISSUE TITLE
V-Bucks not working on builds under 3.5

### ISSUE THREAD

**Issue by sonic11719** [Project-Reload/Reload-Backend#35]
im on 1.8 and i have 500 vbucks but its displaying as 0 vbucks??
![Fortnite Screenshot 2024 10 28 - 00 01 51 32](https://github.com/user-attachments/assets/a6f0595a-4c79-4dd5-988f-4a6891aa273b)

**Comment by burlone0** [comment]
season 1 to 3 are not stable for now

**Comment by sonic11719** [comment]
alr. hopefully this gets fixed soon!
