### ISSUE TITLE
Can't log in in 27.11

### ISSUE THREAD

**Issue by kostasIsHere123** [Project-Reload/Reload-Backend#41]
This either happens when reaching "logging into eos" or just while logging in. Any fix?
![εικόνα_2024-11-02_095238840](https://github.com/user-attachments/assets/9c61ddf9-ae95-4417-907b-3c372d003bdf)
![Στιγμιότυπο οθόνης (344)](https://github.com/user-attachments/assets/0587945c-93ee-4729-a2e1-09a991b32acd)

**Comment by burlone0** [comment]
It's some eos problem, for now we don't support this version. We apologize for this.
