### ISSUE TITLE
Item shop isn't working

### ISSUE THREAD

**Issue by hi15-afk** [Project-Reload/Reload-Backend#43]
Self-explanatory. No offers available

**Comment by kostasIsHere123** [comment]
send a ss of your catalog config

**Comment by hi15-afk** [comment]
> send a ss of your catalog config

I solved the issue, but didn't it auto-rotate?

**Comment by kostasIsHere123** [comment]
did u enable it and set it at the correct time?

**Comment by hi15-afk** [comment]
> did u enable it and set it at the correct time?

Thank you for letting me notice about the time. One last thing, i can't seem to purchase the battle pass. Yes, it is enabled.

**Comment by kostasIsHere123** [comment]
> > did u enable it and set it at the correct time?
> 
> Thank you for letting me notice about the time. One last thing, i can't seem to purchase the battle pass. Yes, it is enabled.

what season?

**Comment by hi15-afk** [comment]
> > > 
> > 
> > 
> > Thank you for letting me notice about the time. One last thing, i can't seem to purchase the battle pass. Yes, it is enabled.

12

**Comment by kostasIsHere123** [comment]
by saying that you cant purchase it, what do you mean?

> > > > 
> > > 
> > > 
> > > Thank you for letting me notice about the time. One last thing, i can't seem to purchase the battle pass. Yes, it is enabled.
> 
> 12

**Comment by hi15-afk** [comment]
> by saying that you cant purchase it, what do you mean?
> 
> > > > > 
> > > > 
> > > > 
> > > > Thank you for letting me notice about the time. One last thing, i can't seem to purchase the battle pass. Yes, it is enabled.
> > 
> > 
> > 12

Clicking on "Confirm purchase" just redirects back to the battle pass. No animation, and the battle pass status is still the same, none.

**Comment by kostasIsHere123** [comment]
thats weird, im not sure how to fix

**Comment by hi15-afk** [comment]
> thats weird, im not sure how to fix

It's okay, i'll wait for another response. Thanks for everything, anyway!

**Comment by kostasIsHere123** [comment]
> > thats weird, im not sure how to fix
> 
> It's okay, i'll wait for another response. Thanks for everything, anyway!

np

**Comment by hi15-afk** [comment]
Update: Restarting my computer & backend apparently did the trick and everything works fine now. Thanks!

> > > thats weird, im not sure how to fix
> > 
> > 
> > It's okay, i'll wait for another response. Thanks for everything, anyway!
> 
> np
