### ISSUE TITLE
"No server found for playlist 2"

### ISSUE THREAD

**Issue by FlowFNMP** [Project-Reload/Reload-Backend#45]
![image](https://github.com/user-attachments/assets/da3eced2-94cf-40fb-a173-04b449230ca5)
![image](https://github.com/user-attachments/assets/65772d8d-3ae8-4398-8592-df708adb9c69)

how do i fix this its with matchmaking

4.2

**Comment by LeproideOFF** [comment]
replace
 "gameServerIP": ["127.0.0.1:7777:2"],
with  "gameServerIP": ["127.0.0.1:7777:playlist_defaultsolo"],
