### ISSUE TITLE
Suggestion (not an issue)

### ISSUE THREAD

**Issue by SKIBIDISAMMAKKO** [Project-Reload/Reload-Backend#53]
Custom playlist display names like from contentpages u can change like Solos playlist displayname from example ”Reload Solos” to ”Reload Solos1”

**Comment by burlone0** [comment]
just go to responses/contentpages.json press **CTRL + F** and search **Playlist_DefaultSolo** once found under **playlist_name** add **"display_name": "Reload Solo"**
