### ISSUE TITLE
season 5 "unknown error, maybe try again?"

### ISSUE THREAD

**Issue by Spincial** [Project-Reload/Reload-Backend#58]
when attempting to matchmake on s5 the game flat out refuses. it will get all the way to "joining server" and then after a few seconds it will give the specified error, ive no idea what the issue is. and the backend acts as if nothing is wrong
![image](https://github.com/user-attachments/assets/51ea6ad7-e6b9-48a3-ba84-887adc7ebc41)
![{4D7C8C15-FE45-43FA-978A-35D17369D40C}](https://github.com/user-attachments/assets/ffb9f91c-bd6f-4dfe-96d1-8a4e19a85867)

**Comment by vlocefn** [comment]
did you setuup fortmatchmaker?

**Comment by Spincial** [comment]
> did you setuup fortmatchmaker?

i shouldn't need to? the backend has a built in one.

**Comment by UniqueTomm** [comment]
> > did you setuup fortmatchmaker?
> 
> i shouldn't need to? the backend has a built in one.

matchmaker dont work below s6

**Comment by R2WW** [comment]
If you are trying the matchmaker in build 5.41 it's broken
5.41 has a broken matchmaker so you might need 1 or change s5 build
